### ISSUE TITLE
Zombie'ish entities glitching through walls on kill.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-2#53]
**Brief Description:**
pig zombies, zombie villagers and regular zombies glitch through walls when killed while stacked

**Instructions:**
have a stack of the above mentioned and kill them close to a wall

**How many times did you recreate this?:**
at least 10 times

**Result:**
the amount of mobs die as defined in the stackmob plugin and sometimes the remaining stack glitches through a wall

**Expected Result:**
mobs to stay in place like any other mob does (this does infact not happen to any of the other mobs)

**Evidence:**
Before:
https://i.imgur.com/m1QDvFy.png
After:
https://i.imgur.com/CVAy7cx.png

**Comment by andrewkm** [comment]
@Nathat23 we are using your very latest build. (Always with the very latest commit you push).

**Comment by JamieSinn** [comment]
My theory on this is that the "safe spawn" mechanic for zombies are preventing them to be spawned in a wall, and overcorrecting into the next block over, or above.
Maybe getting the int value of the coord instead of the double would work better?

**Comment by Gluupor** [comment]
i would guess that @JamieSinn s theory is correct. so its like an inaccuracy or too much accuracy (double values used) that causes this issue.
also ive seen a "slight movement" parameter used in the code which appears to be adding 0.1 to one of the coordinates maybe that has an influence on it as well (im sorry if i mistake the reason for the adding, i just took glance at the code).
i also experienced that when you one hit kill a pig zombie from a stack (jump and hit it in your way down insta kills one/multiple mobs) they wont gain aggro on you and shouldnt start to move towards you (due to aggro) all of a sudden yet the entire stack is being "teleported" towards you usually.

i also experienced that with a different setup on the trap (slabs, iron bars basically less full blocks) it seems as if the glitching happens less often.
![2018-06-05_17 48 01](https://user-images.githubusercontent.com/10635797/40987385-ac517524-68e8-11e8-83ec-2d56714bb795.png)
this would actually fortify @JamieSinn s theory since half blocks or transparent blocks might be considered a "safe spawn"

**Comment by andrewkm** [comment]
Awesome, thanks for the information @Gluupor
