### ISSUE TITLE
Latest changes break exp.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-2#68]
This commit:
https://github.com/Nathat23/StackMob-2/commit/880b2177ff2851888d78d8860a2f3ffc0d17adcb

Broke exp once again on our server.
Reference: https://github.com/Nathat23/StackMob-2/issues/61
Using your default config from latest commit.

How can we reproduce the original behavior we were looking for?
@Gluupor please share your findings on the latest commits here.

**Comment by Gluupor** [comment]
https://github.com/Nathat23/StackMob-2/commit/880b2177ff2851888d78d8860a2f3ffc0d17adcb#diff-eefb1b700e2f82dff8f8cac10b3d58feR30
you need to **multiply** originalexperience with what the parentheses calculates.

https://github.com/Nathat23/StackMob-2/commit/880b2177ff2851888d78d8860a2f3ffc0d17adcb#diff-cffe3129114c8bb7a86d2eb07bb3814bR83
needs to be **multiply-exp.enabled** since you changed the config

https://github.com/Nathat23/StackMob-2/commit/880b2177ff2851888d78d8860a2f3ffc0d17adcb#diff-cffe3129114c8bb7a86d2eb07bb3814bR85
i dont think the experience orb spawned will contain anything if you set the experience it should have after spawning it. so i guess it should be the other way round.

**Comment by Nathat23** [comment]
> you need to multiply originalexperience with what the parentheses calculates.
surely that makes no difference?

**Comment by Gluupor** [comment]
surely it does:

example of a blaze:

originalExperience  = 10
customMultiplier  = 1
entityAmount = 4 (4 killed beyond the first since you get exp for the first per default)

Math.round(originalExperience + ((customMultiplier * entityAmount)))
10 + (1 * 4) = 14

but since i killed 4 im supposed to get 40 (at least in our setup)

Math.round(originalExperience * ((customMultiplier * entityAmount)))

10 * (1*4) = 40
